<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="img\back.png" />
    <None Remove="img\backCabinet.jpg" />
    <None Remove="img\backListWindow.png" />
    <None Remove="img\backLogin2.jpg" />
    <None Remove="img\back\back1.png" />
    <None Remove="img\back\back2.png" />
    <None Remove="img\back\back_default.png" />
    <None Remove="img\back\back_default_small.png" />
    <None Remove="img\back\images.jfif" />
    <None Remove="img\back\q1.jpg" />
    <None Remove="img\back\q2.jpg" />
    <None Remove="img\icon_add.png" />
    <None Remove="img\icon_back.png" />
    <None Remove="img\icon_cabinet.png" />
    <None Remove="img\icon_delete.png" />
    <None Remove="img\icon_heart.png" />
    <None Remove="img\icon_heart2.png" />
    <None Remove="img\icon_save.png" />
    <None Remove="img\icon_start.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\back.png" />
    <Content Include="img\back\back1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="img\back\back2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="img\back\back_default.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="img\back\back_default_small.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="img\back\q1.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="img\back\q2.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="img\backCabinet.jpg" />
    <Resource Include="img\backListWindow.png" />
    <Resource Include="img\backLogin2.jpg" />
    <Resource Include="img\icon_add.png" />
    <Resource Include="img\icon_back.png" />
    <Resource Include="img\icon_cabinet.png" />
    <Resource Include="img\icon_delete.png" />
    <Resource Include="img\icon_heart.png" />
    <Resource Include="img\icon_heart2.png" />
    <Resource Include="img\icon_save.png" />
    <Resource Include="img\icon_start.png" />
  </ItemGroup>

</Project>
